CREATE TABLE products (
    product_id UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    price NUMERIC(10,2),
    quantity INT,
    description VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);