// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamsCreateAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Verified      string                 `protobuf:"bytes,6,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsCreateAdmin) Reset() {
	*x = ParamsCreateAdmin{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsCreateAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsCreateAdmin) ProtoMessage() {}

func (x *ParamsCreateAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsCreateAdmin.ProtoReflect.Descriptor instead.
func (*ParamsCreateAdmin) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ParamsCreateAdmin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParamsCreateAdmin) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ParamsCreateAdmin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ParamsCreateAdmin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ParamsCreateAdmin) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ParamsCreateAdmin) GetVerified() string {
	if x != nil {
		return x.Verified
	}
	return ""
}

type ParamsUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Verified      string                 `protobuf:"bytes,7,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsUser) Reset() {
	*x = ParamsUser{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsUser) ProtoMessage() {}

func (x *ParamsUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsUser.ProtoReflect.Descriptor instead.
func (*ParamsUser) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ParamsUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParamsUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParamsUser) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ParamsUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ParamsUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ParamsUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ParamsUser) GetVerified() string {
	if x != nil {
		return x.Verified
	}
	return ""
}

func (x *ParamsUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ParamsUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ParamsSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsSearchRequest) Reset() {
	*x = ParamsSearchRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsSearchRequest) ProtoMessage() {}

func (x *ParamsSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsSearchRequest.ProtoReflect.Descriptor instead.
func (*ParamsSearchRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ParamsSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ParamsSearchRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ParamsSearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ParamsSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ParamsSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ParamsSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Users         []*ParamsUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsSearchResponse) Reset() {
	*x = ParamsSearchResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsSearchResponse) ProtoMessage() {}

func (x *ParamsSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsSearchResponse.ProtoReflect.Descriptor instead.
func (*ParamsSearchResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ParamsSearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ParamsSearchResponse) GetUsers() []*ParamsUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type ParamsDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsDeleteUserRequest) Reset() {
	*x = ParamsDeleteUserRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsDeleteUserRequest) ProtoMessage() {}

func (x *ParamsDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*ParamsDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ParamsDeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ParamsDeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsDeleteUserResponse) Reset() {
	*x = ParamsDeleteUserResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsDeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsDeleteUserResponse) ProtoMessage() {}

func (x *ParamsDeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsDeleteUserResponse.ProtoReflect.Descriptor instead.
func (*ParamsDeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ParamsDeleteUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\x11ParamsCreateAdmin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\tR\bverified\"\xad\x02\n" +
	"\n" +
	"ParamsUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1a\n" +
	"\bverified\x18\a \x01(\tR\bverified\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x01\n" +
	"\x13ParamsSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"O\n" +
	"\x14ParamsSearchResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12!\n" +
	"\x05users\x18\x02 \x03(\v2\v.ParamsUserR\x05users\"2\n" +
	"\x17ParamsDeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x18ParamsDeleteUserResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xbb\x01\n" +
	"\fAdminService\x12-\n" +
	"\bRegister\x12\x12.ParamsCreateAdmin\x1a\v.ParamsUser\"\x00\x127\n" +
	"\x06Search\x12\x14.ParamsSearchRequest\x1a\x15.ParamsSearchResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteUser\x12\x18.ParamsDeleteUserRequest\x1a\x19.ParamsDeleteUserResponse\"\x00B/Z-github.com/aclgo/grpc-jwt/proto-service/adminb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_proto_goTypes = []any{
	(*ParamsCreateAdmin)(nil),        // 0: ParamsCreateAdmin
	(*ParamsUser)(nil),               // 1: ParamsUser
	(*ParamsSearchRequest)(nil),      // 2: ParamsSearchRequest
	(*ParamsSearchResponse)(nil),     // 3: ParamsSearchResponse
	(*ParamsDeleteUserRequest)(nil),  // 4: ParamsDeleteUserRequest
	(*ParamsDeleteUserResponse)(nil), // 5: ParamsDeleteUserResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_admin_proto_depIdxs = []int32{
	6, // 0: ParamsUser.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: ParamsUser.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: ParamsSearchResponse.users:type_name -> ParamsUser
	0, // 3: AdminService.Register:input_type -> ParamsCreateAdmin
	2, // 4: AdminService.Search:input_type -> ParamsSearchRequest
	4, // 5: AdminService.DeleteUser:input_type -> ParamsDeleteUserRequest
	1, // 6: AdminService.Register:output_type -> ParamsUser
	3, // 7: AdminService.Search:output_type -> ParamsSearchResponse
	5, // 8: AdminService.DeleteUser:output_type -> ParamsDeleteUserResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
