// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	AccountID     string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	ProductsIDS   []string               `protobuf:"bytes,3,rep,name=productsIDS,proto3" json:"productsIDS,omitempty"`
	CreatedAT     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Orders) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *Orders) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *Orders) GetProductsIDS() []string {
	if x != nil {
		return x.ProductsIDS
	}
	return nil
}

func (x *Orders) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

type ParamCreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	ProductsIDS   []string               `protobuf:"bytes,2,rep,name=productsIDS,proto3" json:"productsIDS,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreateOrderRequest) Reset() {
	*x = ParamCreateOrderRequest{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateOrderRequest) ProtoMessage() {}

func (x *ParamCreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateOrderRequest.ProtoReflect.Descriptor instead.
func (*ParamCreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ParamCreateOrderRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetProductsIDS() []string {
	if x != nil {
		return x.ProductsIDS
	}
	return nil
}

type ParamCreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreateOrderResponse) Reset() {
	*x = ParamCreateOrderResponse{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateOrderResponse) ProtoMessage() {}

func (x *ParamCreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateOrderResponse.ProtoReflect.Descriptor instead.
func (*ParamCreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *ParamCreateOrderResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

type ParamFindOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderRequest) Reset() {
	*x = ParamFindOrderRequest{}
	mi := &file_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderRequest) ProtoMessage() {}

func (x *ParamFindOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{3}
}

func (x *ParamFindOrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type ParamFindOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderResponse) Reset() {
	*x = ParamFindOrderResponse{}
	mi := &file_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderResponse) ProtoMessage() {}

func (x *ParamFindOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{4}
}

func (x *ParamFindOrderResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

type ParamFindOrderByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByAccountRequest) Reset() {
	*x = ParamFindOrderByAccountRequest{}
	mi := &file_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByAccountRequest) ProtoMessage() {}

func (x *ParamFindOrderByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByAccountRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByAccountRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ParamFindOrderByAccountRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

type ParamFindOrderByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Orders              `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByAccountResponse) Reset() {
	*x = ParamFindOrderByAccountResponse{}
	mi := &file_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByAccountResponse) ProtoMessage() {}

func (x *ParamFindOrderByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByAccountResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByAccountResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ParamFindOrderByAccountResponse) GetOrders() []*Orders {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ParamFindOrderByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByProductRequest) Reset() {
	*x = ParamFindOrderByProductRequest{}
	mi := &file_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByProductRequest) ProtoMessage() {}

func (x *ParamFindOrderByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByProductRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByProductRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{7}
}

func (x *ParamFindOrderByProductRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type ParamFindOrderByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByProductResponse) Reset() {
	*x = ParamFindOrderByProductResponse{}
	mi := &file_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByProductResponse) ProtoMessage() {}

func (x *ParamFindOrderByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByProductResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByProductResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{8}
}

func (x *ParamFindOrderByProductResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x06Orders\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12 \n" +
	"\vproductsIDS\x18\x03 \x03(\tR\vproductsIDS\x128\n" +
	"\tcreatedAT\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\"Y\n" +
	"\x17ParamCreateOrderRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\x12 \n" +
	"\vproductsIDS\x18\x02 \x03(\tR\vproductsIDS\"9\n" +
	"\x18ParamCreateOrderResponse\x12\x1d\n" +
	"\x05order\x18\x01 \x01(\v2\a.OrdersR\x05order\"1\n" +
	"\x15ParamFindOrderRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\"7\n" +
	"\x16ParamFindOrderResponse\x12\x1d\n" +
	"\x05order\x18\x01 \x01(\v2\a.OrdersR\x05order\">\n" +
	"\x1eParamFindOrderByAccountRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\"B\n" +
	"\x1fParamFindOrderByAccountResponse\x12\x1f\n" +
	"\x06orders\x18\x01 \x03(\v2\a.OrdersR\x06orders\">\n" +
	"\x1eParamFindOrderByProductRequest\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\tR\tproductID\"@\n" +
	"\x1fParamFindOrderByProductResponse\x12\x1d\n" +
	"\x05order\x18\x01 \x01(\v2\a.OrdersR\x05order2\xb8\x02\n" +
	"\fServiceOrder\x12=\n" +
	"\x06Create\x12\x18.ParamCreateOrderRequest\x1a\x19.ParamCreateOrderResponse\x127\n" +
	"\x04Find\x12\x16.ParamFindOrderRequest\x1a\x17.ParamFindOrderResponse\x12W\n" +
	"\x12FindOrderByAccount\x12\x1f.ParamFindOrderByAccountRequest\x1a .ParamFindOrderByAccountResponse\x12W\n" +
	"\x12FindOrderByProduct\x12\x1f.ParamFindOrderByProductRequest\x1a .ParamFindOrderByProductResponseB:Z8github.com/aclgo/simple-api-gateway/proto-service/ordersb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orders_proto_goTypes = []any{
	(*Orders)(nil),                          // 0: Orders
	(*ParamCreateOrderRequest)(nil),         // 1: ParamCreateOrderRequest
	(*ParamCreateOrderResponse)(nil),        // 2: ParamCreateOrderResponse
	(*ParamFindOrderRequest)(nil),           // 3: ParamFindOrderRequest
	(*ParamFindOrderResponse)(nil),          // 4: ParamFindOrderResponse
	(*ParamFindOrderByAccountRequest)(nil),  // 5: ParamFindOrderByAccountRequest
	(*ParamFindOrderByAccountResponse)(nil), // 6: ParamFindOrderByAccountResponse
	(*ParamFindOrderByProductRequest)(nil),  // 7: ParamFindOrderByProductRequest
	(*ParamFindOrderByProductResponse)(nil), // 8: ParamFindOrderByProductResponse
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_orders_proto_depIdxs = []int32{
	9, // 0: Orders.createdAT:type_name -> google.protobuf.Timestamp
	0, // 1: ParamCreateOrderResponse.order:type_name -> Orders
	0, // 2: ParamFindOrderResponse.order:type_name -> Orders
	0, // 3: ParamFindOrderByAccountResponse.orders:type_name -> Orders
	0, // 4: ParamFindOrderByProductResponse.order:type_name -> Orders
	1, // 5: ServiceOrder.Create:input_type -> ParamCreateOrderRequest
	3, // 6: ServiceOrder.Find:input_type -> ParamFindOrderRequest
	5, // 7: ServiceOrder.FindOrderByAccount:input_type -> ParamFindOrderByAccountRequest
	7, // 8: ServiceOrder.FindOrderByProduct:input_type -> ParamFindOrderByProductRequest
	2, // 9: ServiceOrder.Create:output_type -> ParamCreateOrderResponse
	4, // 10: ServiceOrder.Find:output_type -> ParamFindOrderResponse
	6, // 11: ServiceOrder.FindOrderByAccount:output_type -> ParamFindOrderByAccountResponse
	8, // 12: ServiceOrder.FindOrderByProduct:output_type -> ParamFindOrderByProductResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
