// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: orders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_PREMIUM_SUBSCRIPTION   OrderType = 1
	OrderType_BALANCE_DEPOSIT        OrderType = 2
	OrderType_PRODUCT_PURCHASE       OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "PREMIUM_SUBSCRIPTION",
		2: "BALANCE_DEPOSIT",
		3: "PRODUCT_PURCHASE",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"PREMIUM_SUBSCRIPTION":   1,
		"BALANCE_DEPOSIT":        2,
		"PRODUCT_PURCHASE":       3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_orders_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PIX                        PaymentMethod = 1
	PaymentMethod_CREDIT_CARD                PaymentMethod = 2
	PaymentMethod_INTERNAL_BALANCE           PaymentMethod = 3
	PaymentMethod_BOLETO                     PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PIX",
		2: "CREDIT_CARD",
		3: "INTERNAL_BALANCE",
		4: "BOLETO",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PIX":                        1,
		"CREDIT_CARD":                2,
		"INTERNAL_BALANCE":           3,
		"BOLETO":                     4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_orders_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_PENDING                  OrderStatus = 1
	OrderStatus_PAID                     OrderStatus = 2
	OrderStatus_FAILED                   OrderStatus = 3
	OrderStatus_CANCELLED                OrderStatus = 4
	OrderStatus_REFUNDED                 OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PAID",
		3: "FAILED",
		4: "CANCELLED",
		5: "REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"PENDING":                  1,
		"PAID":                     2,
		"FAILED":                   3,
		"CANCELLED":                4,
		"REFUNDED":                 5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orders_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

type Orders struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrderID              string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	AccountID            string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Type                 OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=proto.OrderType" json:"type,omitempty"`
	Amount               int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod        PaymentMethod          `protobuf:"varint,5,opt,name=paymentMethod,proto3,enum=proto.PaymentMethod" json:"paymentMethod,omitempty"`
	Status               OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=proto.OrderStatus" json:"status,omitempty"`
	Metadata             []byte                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	GatewayTransactionID string                 `protobuf:"bytes,8,opt,name=gatewayTransactionID,proto3" json:"gatewayTransactionID,omitempty"`
	PixQRCode            string                 `protobuf:"bytes,9,opt,name=pixQRCode,proto3" json:"pixQRCode,omitempty"`
	PixExpiration        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=pixExpiration,proto3" json:"pixExpiration,omitempty"`
	CardToken            string                 `protobuf:"bytes,11,opt,name=cardToken,proto3" json:"cardToken,omitempty"`
	CardExpiration       string                 `protobuf:"bytes,12,opt,name=cardExpiration,proto3" json:"cardExpiration,omitempty"`
	BoletoURL            string                 `protobuf:"bytes,13,opt,name=boletoURL,proto3" json:"boletoURL,omitempty"`
	BoletoBarcode        string                 `protobuf:"bytes,14,opt,name=boletoBarcode,proto3" json:"boletoBarcode,omitempty"`
	BoletoExpiration     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=boletoExpiration,proto3" json:"boletoExpiration,omitempty"`
	CreatedAT            *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	UpdatedAT            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updatedAT,proto3" json:"updatedAT,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Orders) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *Orders) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *Orders) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Orders) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Orders) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Orders) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Orders) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Orders) GetGatewayTransactionID() string {
	if x != nil {
		return x.GatewayTransactionID
	}
	return ""
}

func (x *Orders) GetPixQRCode() string {
	if x != nil {
		return x.PixQRCode
	}
	return ""
}

func (x *Orders) GetPixExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.PixExpiration
	}
	return nil
}

func (x *Orders) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *Orders) GetCardExpiration() string {
	if x != nil {
		return x.CardExpiration
	}
	return ""
}

func (x *Orders) GetBoletoURL() string {
	if x != nil {
		return x.BoletoURL
	}
	return ""
}

func (x *Orders) GetBoletoBarcode() string {
	if x != nil {
		return x.BoletoBarcode
	}
	return ""
}

func (x *Orders) GetBoletoExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.BoletoExpiration
	}
	return nil
}

func (x *Orders) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

func (x *Orders) GetUpdatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAT
	}
	return nil
}

type ParamCreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountID            string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Type                 OrderType              `protobuf:"varint,2,opt,name=type,proto3,enum=proto.OrderType" json:"type,omitempty"`
	Amount               int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod        PaymentMethod          `protobuf:"varint,4,opt,name=paymentMethod,proto3,enum=proto.PaymentMethod" json:"paymentMethod,omitempty"`
	Status               OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=proto.OrderStatus" json:"status,omitempty"`
	Metadata             []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	GatewayTransactionID string                 `protobuf:"bytes,7,opt,name=gatewayTransactionID,proto3" json:"gatewayTransactionID,omitempty"`
	PixQRCode            string                 `protobuf:"bytes,8,opt,name=pixQRCode,proto3" json:"pixQRCode,omitempty"`
	PixExpiration        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=pixExpiration,proto3" json:"pixExpiration,omitempty"`
	CardToken            string                 `protobuf:"bytes,10,opt,name=cardToken,proto3" json:"cardToken,omitempty"`
	CardExpiration       string                 `protobuf:"bytes,11,opt,name=cardExpiration,proto3" json:"cardExpiration,omitempty"`
	BoletoURL            string                 `protobuf:"bytes,12,opt,name=boletoURL,proto3" json:"boletoURL,omitempty"`
	BoletoBarcode        string                 `protobuf:"bytes,13,opt,name=boletoBarcode,proto3" json:"boletoBarcode,omitempty"`
	BoletoExpiration     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=boletoExpiration,proto3" json:"boletoExpiration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParamCreateOrderRequest) Reset() {
	*x = ParamCreateOrderRequest{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateOrderRequest) ProtoMessage() {}

func (x *ParamCreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateOrderRequest.ProtoReflect.Descriptor instead.
func (*ParamCreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ParamCreateOrderRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *ParamCreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ParamCreateOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *ParamCreateOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ParamCreateOrderRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ParamCreateOrderRequest) GetGatewayTransactionID() string {
	if x != nil {
		return x.GatewayTransactionID
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetPixQRCode() string {
	if x != nil {
		return x.PixQRCode
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetPixExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.PixExpiration
	}
	return nil
}

func (x *ParamCreateOrderRequest) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetCardExpiration() string {
	if x != nil {
		return x.CardExpiration
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetBoletoURL() string {
	if x != nil {
		return x.BoletoURL
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetBoletoBarcode() string {
	if x != nil {
		return x.BoletoBarcode
	}
	return ""
}

func (x *ParamCreateOrderRequest) GetBoletoExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.BoletoExpiration
	}
	return nil
}

type ParamCreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreateOrderResponse) Reset() {
	*x = ParamCreateOrderResponse{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateOrderResponse) ProtoMessage() {}

func (x *ParamCreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateOrderResponse.ProtoReflect.Descriptor instead.
func (*ParamCreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *ParamCreateOrderResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

type ParamFindOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderRequest) Reset() {
	*x = ParamFindOrderRequest{}
	mi := &file_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderRequest) ProtoMessage() {}

func (x *ParamFindOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{3}
}

func (x *ParamFindOrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type ParamFindOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderResponse) Reset() {
	*x = ParamFindOrderResponse{}
	mi := &file_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderResponse) ProtoMessage() {}

func (x *ParamFindOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{4}
}

func (x *ParamFindOrderResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

type ParamFindOrderByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByAccountRequest) Reset() {
	*x = ParamFindOrderByAccountRequest{}
	mi := &file_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByAccountRequest) ProtoMessage() {}

func (x *ParamFindOrderByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByAccountRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByAccountRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ParamFindOrderByAccountRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

type ParamFindOrderByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Orders              `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByAccountResponse) Reset() {
	*x = ParamFindOrderByAccountResponse{}
	mi := &file_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByAccountResponse) ProtoMessage() {}

func (x *ParamFindOrderByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByAccountResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByAccountResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ParamFindOrderByAccountResponse) GetOrders() []*Orders {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ParamFindOrderByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByProductRequest) Reset() {
	*x = ParamFindOrderByProductRequest{}
	mi := &file_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByProductRequest) ProtoMessage() {}

func (x *ParamFindOrderByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByProductRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByProductRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{7}
}

func (x *ParamFindOrderByProductRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type ParamFindOrderByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Orders              `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByProductResponse) Reset() {
	*x = ParamFindOrderByProductResponse{}
	mi := &file_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByProductResponse) ProtoMessage() {}

func (x *ParamFindOrderByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByProductResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByProductResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{8}
}

func (x *ParamFindOrderByProductResponse) GetOrders() []*Orders {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ParamFindOrderByGatewayTransactionIdRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GatewayTransactionId string                 `protobuf:"bytes,1,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParamFindOrderByGatewayTransactionIdRequest) Reset() {
	*x = ParamFindOrderByGatewayTransactionIdRequest{}
	mi := &file_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByGatewayTransactionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByGatewayTransactionIdRequest) ProtoMessage() {}

func (x *ParamFindOrderByGatewayTransactionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByGatewayTransactionIdRequest.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByGatewayTransactionIdRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{9}
}

func (x *ParamFindOrderByGatewayTransactionIdRequest) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

type ParamFindOrderByGatewayTransactionIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFindOrderByGatewayTransactionIdResponse) Reset() {
	*x = ParamFindOrderByGatewayTransactionIdResponse{}
	mi := &file_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFindOrderByGatewayTransactionIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFindOrderByGatewayTransactionIdResponse) ProtoMessage() {}

func (x *ParamFindOrderByGatewayTransactionIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFindOrderByGatewayTransactionIdResponse.ProtoReflect.Descriptor instead.
func (*ParamFindOrderByGatewayTransactionIdResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{10}
}

func (x *ParamFindOrderByGatewayTransactionIdResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

type ParamUpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=proto.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamUpdateOrderStatusRequest) Reset() {
	*x = ParamUpdateOrderStatusRequest{}
	mi := &file_orders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamUpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamUpdateOrderStatusRequest) ProtoMessage() {}

func (x *ParamUpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamUpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*ParamUpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{11}
}

func (x *ParamUpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ParamUpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type ParamUpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamUpdateOrderStatusResponse) Reset() {
	*x = ParamUpdateOrderStatusResponse{}
	mi := &file_orders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamUpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamUpdateOrderStatusResponse) ProtoMessage() {}

func (x *ParamUpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamUpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*ParamUpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{12}
}

func (x *ParamUpdateOrderStatusResponse) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x05\n" +
	"\x06Orders\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.proto.OrderTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12:\n" +
	"\rpaymentMethod\x18\x05 \x01(\x0e2\x14.proto.PaymentMethodR\rpaymentMethod\x12*\n" +
	"\x06status\x18\x06 \x01(\x0e2\x12.proto.OrderStatusR\x06status\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\fR\bmetadata\x122\n" +
	"\x14gatewayTransactionID\x18\b \x01(\tR\x14gatewayTransactionID\x12\x1c\n" +
	"\tpixQRCode\x18\t \x01(\tR\tpixQRCode\x12@\n" +
	"\rpixExpiration\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rpixExpiration\x12\x1c\n" +
	"\tcardToken\x18\v \x01(\tR\tcardToken\x12&\n" +
	"\x0ecardExpiration\x18\f \x01(\tR\x0ecardExpiration\x12\x1c\n" +
	"\tboletoURL\x18\r \x01(\tR\tboletoURL\x12$\n" +
	"\rboletoBarcode\x18\x0e \x01(\tR\rboletoBarcode\x12F\n" +
	"\x10boletoExpiration\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x10boletoExpiration\x128\n" +
	"\tcreatedAT\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\x128\n" +
	"\tupdatedAT\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAT\"\xdf\x04\n" +
	"\x17ParamCreateOrderRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.proto.OrderTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12:\n" +
	"\rpaymentMethod\x18\x04 \x01(\x0e2\x14.proto.PaymentMethodR\rpaymentMethod\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.proto.OrderStatusR\x06status\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\x122\n" +
	"\x14gatewayTransactionID\x18\a \x01(\tR\x14gatewayTransactionID\x12\x1c\n" +
	"\tpixQRCode\x18\b \x01(\tR\tpixQRCode\x12@\n" +
	"\rpixExpiration\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rpixExpiration\x12\x1c\n" +
	"\tcardToken\x18\n" +
	" \x01(\tR\tcardToken\x12&\n" +
	"\x0ecardExpiration\x18\v \x01(\tR\x0ecardExpiration\x12\x1c\n" +
	"\tboletoURL\x18\f \x01(\tR\tboletoURL\x12$\n" +
	"\rboletoBarcode\x18\r \x01(\tR\rboletoBarcode\x12F\n" +
	"\x10boletoExpiration\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x10boletoExpiration\"?\n" +
	"\x18ParamCreateOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.proto.OrdersR\x05order\"1\n" +
	"\x15ParamFindOrderRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\"=\n" +
	"\x16ParamFindOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.proto.OrdersR\x05order\">\n" +
	"\x1eParamFindOrderByAccountRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\"H\n" +
	"\x1fParamFindOrderByAccountResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.proto.OrdersR\x06orders\">\n" +
	"\x1eParamFindOrderByProductRequest\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\tR\tproductID\"H\n" +
	"\x1fParamFindOrderByProductResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.proto.OrdersR\x06orders\"c\n" +
	"+ParamFindOrderByGatewayTransactionIdRequest\x124\n" +
	"\x16gateway_transaction_id\x18\x01 \x01(\tR\x14gatewayTransactionId\"S\n" +
	",ParamFindOrderByGatewayTransactionIdResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.proto.OrdersR\x05order\"f\n" +
	"\x1dParamUpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.proto.OrderStatusR\x06status\"E\n" +
	"\x1eParamUpdateOrderStatusResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.proto.OrdersR\x05order*l\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PREMIUM_SUBSCRIPTION\x10\x01\x12\x13\n" +
	"\x0fBALANCE_DEPOSIT\x10\x02\x12\x14\n" +
	"\x10PRODUCT_PURCHASE\x10\x03*k\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PIX\x10\x01\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x02\x12\x14\n" +
	"\x10INTERNAL_BALANCE\x10\x03\x12\n" +
	"\n" +
	"\x06BOLETO\x10\x04*k\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\f\n" +
	"\bREFUNDED\x10\x052\xd7\x04\n" +
	"\fServiceOrder\x12I\n" +
	"\x06Create\x12\x1e.proto.ParamCreateOrderRequest\x1a\x1f.proto.ParamCreateOrderResponse\x12C\n" +
	"\x04Find\x12\x1c.proto.ParamFindOrderRequest\x1a\x1d.proto.ParamFindOrderResponse\x12c\n" +
	"\x12FindOrderByAccount\x12%.proto.ParamFindOrderByAccountRequest\x1a&.proto.ParamFindOrderByAccountResponse\x12c\n" +
	"\x12FindOrderByProduct\x12%.proto.ParamFindOrderByProductRequest\x1a&.proto.ParamFindOrderByProductResponse\x12\x8a\x01\n" +
	"\x1fFindOrderByGatewayTransactionId\x122.proto.ParamFindOrderByGatewayTransactionIdRequest\x1a3.proto.ParamFindOrderByGatewayTransactionIdResponse\x12`\n" +
	"\x11UpdateOrderStatus\x12$.proto.ParamUpdateOrderStatusRequest\x1a%.proto.ParamUpdateOrderStatusResponseB\x18Z\x16github.com/aclgo/protob\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orders_proto_goTypes = []any{
	(OrderType)(0),                                       // 0: proto.OrderType
	(PaymentMethod)(0),                                   // 1: proto.PaymentMethod
	(OrderStatus)(0),                                     // 2: proto.OrderStatus
	(*Orders)(nil),                                       // 3: proto.Orders
	(*ParamCreateOrderRequest)(nil),                      // 4: proto.ParamCreateOrderRequest
	(*ParamCreateOrderResponse)(nil),                     // 5: proto.ParamCreateOrderResponse
	(*ParamFindOrderRequest)(nil),                        // 6: proto.ParamFindOrderRequest
	(*ParamFindOrderResponse)(nil),                       // 7: proto.ParamFindOrderResponse
	(*ParamFindOrderByAccountRequest)(nil),               // 8: proto.ParamFindOrderByAccountRequest
	(*ParamFindOrderByAccountResponse)(nil),              // 9: proto.ParamFindOrderByAccountResponse
	(*ParamFindOrderByProductRequest)(nil),               // 10: proto.ParamFindOrderByProductRequest
	(*ParamFindOrderByProductResponse)(nil),              // 11: proto.ParamFindOrderByProductResponse
	(*ParamFindOrderByGatewayTransactionIdRequest)(nil),  // 12: proto.ParamFindOrderByGatewayTransactionIdRequest
	(*ParamFindOrderByGatewayTransactionIdResponse)(nil), // 13: proto.ParamFindOrderByGatewayTransactionIdResponse
	(*ParamUpdateOrderStatusRequest)(nil),                // 14: proto.ParamUpdateOrderStatusRequest
	(*ParamUpdateOrderStatusResponse)(nil),               // 15: proto.ParamUpdateOrderStatusResponse
	(*timestamppb.Timestamp)(nil),                        // 16: google.protobuf.Timestamp
}
var file_orders_proto_depIdxs = []int32{
	0,  // 0: proto.Orders.type:type_name -> proto.OrderType
	1,  // 1: proto.Orders.paymentMethod:type_name -> proto.PaymentMethod
	2,  // 2: proto.Orders.status:type_name -> proto.OrderStatus
	16, // 3: proto.Orders.pixExpiration:type_name -> google.protobuf.Timestamp
	16, // 4: proto.Orders.boletoExpiration:type_name -> google.protobuf.Timestamp
	16, // 5: proto.Orders.createdAT:type_name -> google.protobuf.Timestamp
	16, // 6: proto.Orders.updatedAT:type_name -> google.protobuf.Timestamp
	0,  // 7: proto.ParamCreateOrderRequest.type:type_name -> proto.OrderType
	1,  // 8: proto.ParamCreateOrderRequest.paymentMethod:type_name -> proto.PaymentMethod
	2,  // 9: proto.ParamCreateOrderRequest.status:type_name -> proto.OrderStatus
	16, // 10: proto.ParamCreateOrderRequest.pixExpiration:type_name -> google.protobuf.Timestamp
	16, // 11: proto.ParamCreateOrderRequest.boletoExpiration:type_name -> google.protobuf.Timestamp
	3,  // 12: proto.ParamCreateOrderResponse.order:type_name -> proto.Orders
	3,  // 13: proto.ParamFindOrderResponse.order:type_name -> proto.Orders
	3,  // 14: proto.ParamFindOrderByAccountResponse.orders:type_name -> proto.Orders
	3,  // 15: proto.ParamFindOrderByProductResponse.orders:type_name -> proto.Orders
	3,  // 16: proto.ParamFindOrderByGatewayTransactionIdResponse.order:type_name -> proto.Orders
	2,  // 17: proto.ParamUpdateOrderStatusRequest.status:type_name -> proto.OrderStatus
	3,  // 18: proto.ParamUpdateOrderStatusResponse.order:type_name -> proto.Orders
	4,  // 19: proto.ServiceOrder.Create:input_type -> proto.ParamCreateOrderRequest
	6,  // 20: proto.ServiceOrder.Find:input_type -> proto.ParamFindOrderRequest
	8,  // 21: proto.ServiceOrder.FindOrderByAccount:input_type -> proto.ParamFindOrderByAccountRequest
	10, // 22: proto.ServiceOrder.FindOrderByProduct:input_type -> proto.ParamFindOrderByProductRequest
	12, // 23: proto.ServiceOrder.FindOrderByGatewayTransactionId:input_type -> proto.ParamFindOrderByGatewayTransactionIdRequest
	14, // 24: proto.ServiceOrder.UpdateOrderStatus:input_type -> proto.ParamUpdateOrderStatusRequest
	5,  // 25: proto.ServiceOrder.Create:output_type -> proto.ParamCreateOrderResponse
	7,  // 26: proto.ServiceOrder.Find:output_type -> proto.ParamFindOrderResponse
	9,  // 27: proto.ServiceOrder.FindOrderByAccount:output_type -> proto.ParamFindOrderByAccountResponse
	11, // 28: proto.ServiceOrder.FindOrderByProduct:output_type -> proto.ParamFindOrderByProductResponse
	13, // 29: proto.ServiceOrder.FindOrderByGatewayTransactionId:output_type -> proto.ParamFindOrderByGatewayTransactionIdResponse
	15, // 30: proto.ServiceOrder.UpdateOrderStatus:output_type -> proto.ParamUpdateOrderStatusResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		EnumInfos:         file_orders_proto_enumTypes,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
