// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: orders.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceOrder_Create_FullMethodName             = "/ServiceOrder/Create"
	ServiceOrder_Find_FullMethodName               = "/ServiceOrder/Find"
	ServiceOrder_FindOrderByAccount_FullMethodName = "/ServiceOrder/FindOrderByAccount"
	ServiceOrder_FindOrderByProduct_FullMethodName = "/ServiceOrder/FindOrderByProduct"
)

// ServiceOrderClient is the client API for ServiceOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceOrderClient interface {
	Create(ctx context.Context, in *ParamCreateOrderRequest, opts ...grpc.CallOption) (*ParamCreateOrderResponse, error)
	Find(ctx context.Context, in *ParamFindOrderRequest, opts ...grpc.CallOption) (*ParamFindOrderResponse, error)
	FindOrderByAccount(ctx context.Context, in *ParamFindOrderByAccountRequest, opts ...grpc.CallOption) (*ParamFindOrderByAccountResponse, error)
	FindOrderByProduct(ctx context.Context, in *ParamFindOrderByProductRequest, opts ...grpc.CallOption) (*ParamFindOrderByProductResponse, error)
}

type serviceOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOrderClient(cc grpc.ClientConnInterface) ServiceOrderClient {
	return &serviceOrderClient{cc}
}

func (c *serviceOrderClient) Create(ctx context.Context, in *ParamCreateOrderRequest, opts ...grpc.CallOption) (*ParamCreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamCreateOrderResponse)
	err := c.cc.Invoke(ctx, ServiceOrder_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceOrderClient) Find(ctx context.Context, in *ParamFindOrderRequest, opts ...grpc.CallOption) (*ParamFindOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamFindOrderResponse)
	err := c.cc.Invoke(ctx, ServiceOrder_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceOrderClient) FindOrderByAccount(ctx context.Context, in *ParamFindOrderByAccountRequest, opts ...grpc.CallOption) (*ParamFindOrderByAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamFindOrderByAccountResponse)
	err := c.cc.Invoke(ctx, ServiceOrder_FindOrderByAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceOrderClient) FindOrderByProduct(ctx context.Context, in *ParamFindOrderByProductRequest, opts ...grpc.CallOption) (*ParamFindOrderByProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamFindOrderByProductResponse)
	err := c.cc.Invoke(ctx, ServiceOrder_FindOrderByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOrderServer is the server API for ServiceOrder service.
// All implementations must embed UnimplementedServiceOrderServer
// for forward compatibility.
type ServiceOrderServer interface {
	Create(context.Context, *ParamCreateOrderRequest) (*ParamCreateOrderResponse, error)
	Find(context.Context, *ParamFindOrderRequest) (*ParamFindOrderResponse, error)
	FindOrderByAccount(context.Context, *ParamFindOrderByAccountRequest) (*ParamFindOrderByAccountResponse, error)
	FindOrderByProduct(context.Context, *ParamFindOrderByProductRequest) (*ParamFindOrderByProductResponse, error)
	mustEmbedUnimplementedServiceOrderServer()
}

// UnimplementedServiceOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceOrderServer struct{}

func (UnimplementedServiceOrderServer) Create(context.Context, *ParamCreateOrderRequest) (*ParamCreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedServiceOrderServer) Find(context.Context, *ParamFindOrderRequest) (*ParamFindOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedServiceOrderServer) FindOrderByAccount(context.Context, *ParamFindOrderByAccountRequest) (*ParamFindOrderByAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOrderByAccount not implemented")
}
func (UnimplementedServiceOrderServer) FindOrderByProduct(context.Context, *ParamFindOrderByProductRequest) (*ParamFindOrderByProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOrderByProduct not implemented")
}
func (UnimplementedServiceOrderServer) mustEmbedUnimplementedServiceOrderServer() {}
func (UnimplementedServiceOrderServer) testEmbeddedByValue()                      {}

// UnsafeServiceOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceOrderServer will
// result in compilation errors.
type UnsafeServiceOrderServer interface {
	mustEmbedUnimplementedServiceOrderServer()
}

func RegisterServiceOrderServer(s grpc.ServiceRegistrar, srv ServiceOrderServer) {
	// If the following call panics, it indicates UnimplementedServiceOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceOrder_ServiceDesc, srv)
}

func _ServiceOrder_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOrderServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceOrder_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOrderServer).Create(ctx, req.(*ParamCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceOrder_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamFindOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOrderServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceOrder_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOrderServer).Find(ctx, req.(*ParamFindOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceOrder_FindOrderByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamFindOrderByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOrderServer).FindOrderByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceOrder_FindOrderByAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOrderServer).FindOrderByAccount(ctx, req.(*ParamFindOrderByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceOrder_FindOrderByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamFindOrderByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOrderServer).FindOrderByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceOrder_FindOrderByProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOrderServer).FindOrderByProduct(ctx, req.(*ParamFindOrderByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceOrder_ServiceDesc is the grpc.ServiceDesc for ServiceOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceOrder",
	HandlerType: (*ServiceOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServiceOrder_Create_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ServiceOrder_Find_Handler,
		},
		{
			MethodName: "FindOrderByAccount",
			Handler:    _ServiceOrder_FindOrderByAccount_Handler,
		},
		{
			MethodName: "FindOrderByProduct",
			Handler:    _ServiceOrder_FindOrderByProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders.proto",
}
