// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: balance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamCreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreateWalletRequest) Reset() {
	*x = ParamCreateWalletRequest{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateWalletRequest) ProtoMessage() {}

func (x *ParamCreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateWalletRequest.ProtoReflect.Descriptor instead.
func (*ParamCreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

func (x *ParamCreateWalletRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

type ParamCreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	AccountID     string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAT     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	UpdatedAT     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAT,proto3" json:"updatedAT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreateWalletResponse) Reset() {
	*x = ParamCreateWalletResponse{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreateWalletResponse) ProtoMessage() {}

func (x *ParamCreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreateWalletResponse.ProtoReflect.Descriptor instead.
func (*ParamCreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *ParamCreateWalletResponse) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamCreateWalletResponse) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamCreateWalletResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ParamCreateWalletResponse) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

func (x *ParamCreateWalletResponse) GetUpdatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAT
	}
	return nil
}

type ParamCreditWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreditWalletRequest) Reset() {
	*x = ParamCreditWalletRequest{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreditWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreditWalletRequest) ProtoMessage() {}

func (x *ParamCreditWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreditWalletRequest.ProtoReflect.Descriptor instead.
func (*ParamCreditWalletRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *ParamCreditWalletRequest) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamCreditWalletRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ParamCreditWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	AccountID     string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAT     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	UpdatedAT     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAT,proto3" json:"updatedAT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamCreditWalletResponse) Reset() {
	*x = ParamCreditWalletResponse{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamCreditWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamCreditWalletResponse) ProtoMessage() {}

func (x *ParamCreditWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamCreditWalletResponse.ProtoReflect.Descriptor instead.
func (*ParamCreditWalletResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *ParamCreditWalletResponse) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamCreditWalletResponse) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamCreditWalletResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ParamCreditWalletResponse) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

func (x *ParamCreditWalletResponse) GetUpdatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAT
	}
	return nil
}

type ParamDebitWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamDebitWalletRequest) Reset() {
	*x = ParamDebitWalletRequest{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamDebitWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamDebitWalletRequest) ProtoMessage() {}

func (x *ParamDebitWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamDebitWalletRequest.ProtoReflect.Descriptor instead.
func (*ParamDebitWalletRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *ParamDebitWalletRequest) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamDebitWalletRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ParamDebitWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	AccountID     string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAT     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	UpdatedAT     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAT,proto3" json:"updatedAT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamDebitWalletResponse) Reset() {
	*x = ParamDebitWalletResponse{}
	mi := &file_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamDebitWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamDebitWalletResponse) ProtoMessage() {}

func (x *ParamDebitWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamDebitWalletResponse.ProtoReflect.Descriptor instead.
func (*ParamDebitWalletResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ParamDebitWalletResponse) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamDebitWalletResponse) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamDebitWalletResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ParamDebitWalletResponse) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

func (x *ParamDebitWalletResponse) GetUpdatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAT
	}
	return nil
}

type ParamGetWalletByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamGetWalletByAccountRequest) Reset() {
	*x = ParamGetWalletByAccountRequest{}
	mi := &file_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamGetWalletByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamGetWalletByAccountRequest) ProtoMessage() {}

func (x *ParamGetWalletByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamGetWalletByAccountRequest.ProtoReflect.Descriptor instead.
func (*ParamGetWalletByAccountRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{6}
}

func (x *ParamGetWalletByAccountRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

type ParamgGetWalletByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletID      string                 `protobuf:"bytes,1,opt,name=walletID,proto3" json:"walletID,omitempty"`
	AccountID     string                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAT     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAT,proto3" json:"createdAT,omitempty"`
	UpdatedAT     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAT,proto3" json:"updatedAT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamgGetWalletByAccountResponse) Reset() {
	*x = ParamgGetWalletByAccountResponse{}
	mi := &file_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamgGetWalletByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamgGetWalletByAccountResponse) ProtoMessage() {}

func (x *ParamgGetWalletByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamgGetWalletByAccountResponse.ProtoReflect.Descriptor instead.
func (*ParamgGetWalletByAccountResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{7}
}

func (x *ParamgGetWalletByAccountResponse) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *ParamgGetWalletByAccountResponse) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ParamgGetWalletByAccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ParamgGetWalletByAccountResponse) GetCreatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAT
	}
	return nil
}

func (x *ParamgGetWalletByAccountResponse) GetUpdatedAT() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAT
	}
	return nil
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x18ParamCreateWalletRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\"\xe3\x01\n" +
	"\x19ParamCreateWalletResponse\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x128\n" +
	"\tcreatedAT\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\x128\n" +
	"\tupdatedAT\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAT\"N\n" +
	"\x18ParamCreditWalletRequest\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\xe3\x01\n" +
	"\x19ParamCreditWalletResponse\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x128\n" +
	"\tcreatedAT\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\x128\n" +
	"\tupdatedAT\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAT\"M\n" +
	"\x17ParamDebitWalletRequest\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\xe2\x01\n" +
	"\x18ParamDebitWalletResponse\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x128\n" +
	"\tcreatedAT\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\x128\n" +
	"\tupdatedAT\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAT\">\n" +
	"\x1eParamGetWalletByAccountRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\"\xea\x01\n" +
	" ParamgGetWalletByAccountResponse\x12\x1a\n" +
	"\bwalletID\x18\x01 \x01(\tR\bwalletID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\tR\taccountID\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x128\n" +
	"\tcreatedAT\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAT\x128\n" +
	"\tupdatedAT\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAT2\xa9\x02\n" +
	"\rWalletService\x12?\n" +
	"\x06Create\x12\x19.ParamCreateWalletRequest\x1a\x1a.ParamCreateWalletResponse\x12?\n" +
	"\x06Credit\x12\x19.ParamCreditWalletRequest\x1a\x1a.ParamCreditWalletResponse\x12<\n" +
	"\x05Debit\x12\x18.ParamDebitWalletRequest\x1a\x19.ParamDebitWalletResponse\x12X\n" +
	"\x12GetWalletByAccount\x12\x1f.ParamGetWalletByAccountRequest\x1a!.ParamgGetWalletByAccountResponseB$Z\"github.com/aclgo/gprc-Wallet/protob\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_balance_proto_goTypes = []any{
	(*ParamCreateWalletRequest)(nil),         // 0: ParamCreateWalletRequest
	(*ParamCreateWalletResponse)(nil),        // 1: ParamCreateWalletResponse
	(*ParamCreditWalletRequest)(nil),         // 2: ParamCreditWalletRequest
	(*ParamCreditWalletResponse)(nil),        // 3: ParamCreditWalletResponse
	(*ParamDebitWalletRequest)(nil),          // 4: ParamDebitWalletRequest
	(*ParamDebitWalletResponse)(nil),         // 5: ParamDebitWalletResponse
	(*ParamGetWalletByAccountRequest)(nil),   // 6: ParamGetWalletByAccountRequest
	(*ParamgGetWalletByAccountResponse)(nil), // 7: ParamgGetWalletByAccountResponse
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
}
var file_balance_proto_depIdxs = []int32{
	8,  // 0: ParamCreateWalletResponse.createdAT:type_name -> google.protobuf.Timestamp
	8,  // 1: ParamCreateWalletResponse.updatedAT:type_name -> google.protobuf.Timestamp
	8,  // 2: ParamCreditWalletResponse.createdAT:type_name -> google.protobuf.Timestamp
	8,  // 3: ParamCreditWalletResponse.updatedAT:type_name -> google.protobuf.Timestamp
	8,  // 4: ParamDebitWalletResponse.createdAT:type_name -> google.protobuf.Timestamp
	8,  // 5: ParamDebitWalletResponse.updatedAT:type_name -> google.protobuf.Timestamp
	8,  // 6: ParamgGetWalletByAccountResponse.createdAT:type_name -> google.protobuf.Timestamp
	8,  // 7: ParamgGetWalletByAccountResponse.updatedAT:type_name -> google.protobuf.Timestamp
	0,  // 8: WalletService.Create:input_type -> ParamCreateWalletRequest
	2,  // 9: WalletService.Credit:input_type -> ParamCreditWalletRequest
	4,  // 10: WalletService.Debit:input_type -> ParamDebitWalletRequest
	6,  // 11: WalletService.GetWalletByAccount:input_type -> ParamGetWalletByAccountRequest
	1,  // 12: WalletService.Create:output_type -> ParamCreateWalletResponse
	3,  // 13: WalletService.Credit:output_type -> ParamCreditWalletResponse
	5,  // 14: WalletService.Debit:output_type -> ParamDebitWalletResponse
	7,  // 15: WalletService.GetWalletByAccount:output_type -> ParamgGetWalletByAccountResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
